import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getServerSession} from "next-auth";
import ApolloWrapper from "@/components/apollo-wrapper";
import SessionProvider from "@/components/session-provider";
import Navbar from "@/components/navbar";

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <SessionProvider session={session}>
            <main className='h-[100%]'>
              <Navbar />
              {children}
            </main>
          </SessionProvider>
        </ApolloWrapper>
      </body>
    </html>
  )
}
